news_homepage:
    pattern:  /
    defaults: { _controller: BladeTesterLightNewsBundle:Default:index }

news_add:
    pattern:  /add
    defaults: { _controller: BladeTesterLightNewsBundle:Admin:add }

news_remove:
    pattern:  /{id}/remove
    defaults: { _controller: BladeTesterLightNewsBundle:Admin:remove }
